[theme]
base = "light"
primaryColor = "#F7941D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F0FA"
textColor = "#4B2876"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
